name: Deploy Laravel Gastos to Nomad

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: self-hosted 

    steps:
      - name: Check out del código directo al NFS 📂
        uses: actions/checkout@v4

  
